// This file is auto-generated. Do not edit manually.
// Run scripts/generate.ts to regenerate.

export const RESOURCE_OPERATIONS = {
  "absencetransactions": {
    "getList": { path: "/3/absencetransactions" as const, method: "get" as const },
    "create": { path: "/3/absencetransactions" as const, method: "post" as const },
    "get": { path: "/3/absencetransactions/{id}" as const, method: "get" as const },
    "update": { path: "/3/absencetransactions/{id}" as const, method: "put" as const },
    "delete": { path: "/3/absencetransactions/{id}" as const, method: "delete" as const },
    "listByEmployeeDateCode": { path: "/3/absencetransactions/{id}/{Date}/{Code}" as const, method: "get" as const },
  },
  "accountcharts": {
    "getList": { path: "/3/accountcharts" as const, method: "get" as const },
  },
  "accounts": {
    "getList": { path: "/3/accounts" as const, method: "get" as const },
    "create": { path: "/3/accounts" as const, method: "post" as const },
    "get": { path: "/3/accounts/{Number}" as const, method: "get" as const },
    "update": { path: "/3/accounts/{Number}" as const, method: "put" as const },
    "delete": { path: "/3/accounts/{Number}" as const, method: "delete" as const },
  },
  "archive": {
    "getByPath": { path: "/3/archive" as const, method: "get" as const },
    "upload": { path: "/3/archive" as const, method: "post" as const },
    "deleteByPath": { path: "/3/archive" as const, method: "delete" as const },
    "getById": { path: "/3/archive/{id}" as const, method: "get" as const },
    "deleteById": { path: "/3/archive/{id}" as const, method: "delete" as const },
  },
  "articlefileconnections": {
    "getList": { path: "/3/articlefileconnections" as const, method: "get" as const },
    "create": { path: "/3/articlefileconnections" as const, method: "post" as const },
    "get": { path: "/3/articlefileconnections/{FileId}" as const, method: "get" as const },
    "delete": { path: "/3/articlefileconnections/{FileId}" as const, method: "delete" as const },
  },
  "articles": {
    "getList": { path: "/3/articles" as const, method: "get" as const },
    "create": { path: "/3/articles" as const, method: "post" as const },
    "get": { path: "/3/articles/{ArticleNumber}" as const, method: "get" as const },
    "update": { path: "/3/articles/{ArticleNumber}" as const, method: "put" as const },
    "delete": { path: "/3/articles/{ArticleNumber}" as const, method: "delete" as const },
  },
  "articleurlconnections": {
    "getList": { path: "/3/articleurlconnections" as const, method: "get" as const },
    "create": { path: "/3/articleurlconnections" as const, method: "post" as const },
    "get": { path: "/3/articleurlconnections/{id}" as const, method: "get" as const },
    "update": { path: "/3/articleurlconnections/{id}" as const, method: "put" as const },
    "delete": { path: "/3/articleurlconnections/{id}" as const, method: "delete" as const },
  },
  "assetfileconnections": {
    "getList": { path: "/3/assetfileconnections" as const, method: "get" as const },
    "create": { path: "/3/assetfileconnections" as const, method: "post" as const },
    "delete": { path: "/3/assetfileconnections/{FileId}" as const, method: "delete" as const },
  },
  "assets": {
    "getList": { path: "/3/assets" as const, method: "get" as const },
    "create": { path: "/3/assets" as const, method: "post" as const },
    "changeOb": { path: "/3/assets/changeob/{Id}" as const, method: "put" as const },
    "depreciate": { path: "/3/assets/depreciate" as const, method: "post" as const },
    "listDepreciations": { path: "/3/assets/depreciations/{ToDate}" as const, method: "get" as const },
    "scrap": { path: "/3/assets/scrap/{Id}" as const, method: "put" as const },
    "sell": { path: "/3/assets/sell/{Id}" as const, method: "put" as const },
    "listTypes": { path: "/3/assets/types" as const, method: "get" as const },
    "createType": { path: "/3/assets/types" as const, method: "post" as const },
    "getType": { path: "/3/assets/types/{id}" as const, method: "get" as const },
    "updateType": { path: "/3/assets/types/{id}" as const, method: "put" as const },
    "deleteType": { path: "/3/assets/types/{id}" as const, method: "delete" as const },
    "writeDown": { path: "/3/assets/writedown/{Id}" as const, method: "put" as const },
    "writeUp": { path: "/3/assets/writeup/{Id}" as const, method: "put" as const },
    "get": { path: "/3/assets/{Id}" as const, method: "get" as const },
    "update": { path: "/3/assets/{Id}" as const, method: "put" as const },
    "delete": { path: "/3/assets/{Id}" as const, method: "delete" as const },
  },
  "attendancetransactions": {
    "getList": { path: "/3/attendancetransactions" as const, method: "get" as const },
    "create": { path: "/3/attendancetransactions" as const, method: "post" as const },
    "get": { path: "/3/attendancetransactions/{id}" as const, method: "get" as const },
    "update": { path: "/3/attendancetransactions/{id}" as const, method: "put" as const },
    "delete": { path: "/3/attendancetransactions/{id}" as const, method: "delete" as const },
    "listByEmployeeDateCode": { path: "/3/attendancetransactions/{id}/{Date}/{Code}" as const, method: "get" as const },
  },
  "companyinformation": {
    "get": { path: "/3/companyinformation" as const, method: "get" as const },
  },
  "contractaccruals": {
    "getList": { path: "/3/contractaccruals" as const, method: "get" as const },
    "create": { path: "/3/contractaccruals" as const, method: "post" as const },
    "get": { path: "/3/contractaccruals/{DocumentNumber}" as const, method: "get" as const },
    "update": { path: "/3/contractaccruals/{DocumentNumber}" as const, method: "put" as const },
    "delete": { path: "/3/contractaccruals/{DocumentNumber}" as const, method: "delete" as const },
  },
  "contracts": {
    "getList": { path: "/3/contracts" as const, method: "get" as const },
    "create": { path: "/3/contracts" as const, method: "post" as const },
    "get": { path: "/3/contracts/{DocumentNumber}" as const, method: "get" as const },
    "update": { path: "/3/contracts/{DocumentNumber}" as const, method: "put" as const },
    "createInvoice": { path: "/3/contracts/{DocumentNumber}/createinvoice" as const, method: "put" as const },
    "finish": { path: "/3/contracts/{DocumentNumber}/finish" as const, method: "put" as const },
    "increaseInvoiceCount": { path: "/3/contracts/{DocumentNumber}/increaseinvoicecount" as const, method: "put" as const },
  },
  "contracttemplates": {
    "getList": { path: "/3/contracttemplates" as const, method: "get" as const },
    "create": { path: "/3/contracttemplates" as const, method: "post" as const },
    "get": { path: "/3/contracttemplates/{TemplateNumber}" as const, method: "get" as const },
    "update": { path: "/3/contracttemplates/{TemplateNumber}" as const, method: "put" as const },
  },
  "costcenters": {
    "getList": { path: "/3/costcenters" as const, method: "get" as const },
    "create": { path: "/3/costcenters" as const, method: "post" as const },
    "get": { path: "/3/costcenters/{Code}" as const, method: "get" as const },
    "update": { path: "/3/costcenters/{Code}" as const, method: "put" as const },
    "delete": { path: "/3/costcenters/{Code}" as const, method: "delete" as const },
  },
  "currencies": {
    "getList": { path: "/3/currencies" as const, method: "get" as const },
    "create": { path: "/3/currencies" as const, method: "post" as const },
    "get": { path: "/3/currencies/{Code}" as const, method: "get" as const },
    "update": { path: "/3/currencies/{Code}" as const, method: "put" as const },
    "delete": { path: "/3/currencies/{Code}" as const, method: "delete" as const },
  },
  "customerreferences": {
    "getList": { path: "/3/customerreferences" as const, method: "get" as const },
    "create": { path: "/3/customerreferences" as const, method: "post" as const },
    "get": { path: "/3/customerreferences/{CustomerReferenceRowId}" as const, method: "get" as const },
    "update": { path: "/3/customerreferences/{CustomerReferenceRowId}" as const, method: "put" as const },
    "delete": { path: "/3/customerreferences/{CustomerReferenceRowId}" as const, method: "delete" as const },
  },
  "customers": {
    "getList": { path: "/3/customers" as const, method: "get" as const },
    "create": { path: "/3/customers" as const, method: "post" as const },
    "get": { path: "/3/customers/{CustomerNumber}" as const, method: "get" as const },
    "update": { path: "/3/customers/{CustomerNumber}" as const, method: "put" as const },
    "delete": { path: "/3/customers/{CustomerNumber}" as const, method: "delete" as const },
  },
  "emailsenders": {
    "getList": { path: "/3/emailsenders" as const, method: "get" as const },
    "addTrusted": { path: "/3/emailsenders/trusted" as const, method: "post" as const },
    "removeTrusted": { path: "/3/emailsenders/trusted/{Id}" as const, method: "delete" as const },
  },
  "employees": {
    "getList": { path: "/3/employees" as const, method: "get" as const },
    "create": { path: "/3/employees" as const, method: "post" as const },
    "get": { path: "/3/employees/{EmployeeId}" as const, method: "get" as const },
    "update": { path: "/3/employees/{EmployeeId}" as const, method: "put" as const },
  },
  "euvatlimitregulation": {
    "get": { path: "/3/euvatlimitregulation" as const, method: "get" as const },
  },
  "expenses": {
    "getList": { path: "/3/expenses" as const, method: "get" as const },
    "create": { path: "/3/expenses" as const, method: "post" as const },
    "get": { path: "/3/expenses/{ExpenseCode}" as const, method: "get" as const },
  },
  "fileattachments": {
    "getList": { path: "/api/fileattachments/attachments-v1" as const, method: "get" as const },
    "attach": { path: "/api/fileattachments/attachments-v1" as const, method: "post" as const },
    "getNumberOfAttachments": { path: "/api/fileattachments/attachments-v1/numberofattachments" as const, method: "get" as const },
    "validateIncludedOnSend": { path: "/api/fileattachments/attachments-v1/validateincludedonsend" as const, method: "post" as const },
    "update": { path: "/api/fileattachments/attachments-v1/{attachmentId}" as const, method: "put" as const },
    "detach": { path: "/api/fileattachments/attachments-v1/{attachmentId}" as const, method: "delete" as const },
  },
  "financialyears": {
    "getList": { path: "/3/financialyears" as const, method: "get" as const },
    "create": { path: "/3/financialyears" as const, method: "post" as const },
    "get": { path: "/3/financialyears/{Id}" as const, method: "get" as const },
  },
  "inbox": {
    "getList": { path: "/3/inbox" as const, method: "get" as const },
    "upload": { path: "/3/inbox" as const, method: "post" as const },
    "get": { path: "/3/inbox/{Id}" as const, method: "get" as const },
    "delete": { path: "/3/inbox/{Id}" as const, method: "delete" as const },
  },
  "integrationDeveloper": {
    "listRatings": { path: "/api/integration-developer/ratings-v1" as const, method: "get" as const },
    "getSalesForIntegration": { path: "/api/integration-developer/sales-v1/{integrationId}" as const, method: "get" as const },
    "getUsersForIntegrationAndTenant": { path: "/api/integration-developer/users/users-v1/{integrationId}/{tenantId}" as const, method: "get" as const },
  },
  "integrationPartner": {
    "getSalesForApp": { path: "/api/integration-partner/apps/sales-v1/{appId}" as const, method: "get" as const },
    "getSalesForAppAndTenant": { path: "/api/integration-partner/apps/sales-v1/{appId}/{tenantId}" as const, method: "get" as const },
  },
  "invoiceaccruals": {
    "getList": { path: "/3/invoiceaccruals" as const, method: "get" as const },
    "create": { path: "/3/invoiceaccruals" as const, method: "post" as const },
    "get": { path: "/3/invoiceaccruals/{InvoiceNumber}" as const, method: "get" as const },
    "update": { path: "/3/invoiceaccruals/{InvoiceNumber}" as const, method: "put" as const },
    "delete": { path: "/3/invoiceaccruals/{InvoiceNumber}" as const, method: "delete" as const },
  },
  "invoicepayments": {
    "getList": { path: "/3/invoicepayments" as const, method: "get" as const },
    "create": { path: "/3/invoicepayments" as const, method: "post" as const },
    "get": { path: "/3/invoicepayments/{Number}" as const, method: "get" as const },
    "update": { path: "/3/invoicepayments/{Number}" as const, method: "put" as const },
    "delete": { path: "/3/invoicepayments/{Number}" as const, method: "delete" as const },
    "bookkeep": { path: "/3/invoicepayments/{Number}/bookkeep" as const, method: "put" as const },
  },
  "invoices": {
    "getList": { path: "/3/invoices" as const, method: "get" as const },
    "create": { path: "/3/invoices" as const, method: "post" as const },
    "get": { path: "/3/invoices/{DocumentNumber}" as const, method: "get" as const },
    "update": { path: "/3/invoices/{DocumentNumber}" as const, method: "put" as const },
    "bookkeep": { path: "/3/invoices/{DocumentNumber}/bookkeep" as const, method: "put" as const },
    "cancel": { path: "/3/invoices/{DocumentNumber}/cancel" as const, method: "put" as const },
    "credit": { path: "/3/invoices/{DocumentNumber}/credit" as const, method: "put" as const },
    "sendEinvoice": { path: "/3/invoices/{DocumentNumber}/einvoice" as const, method: "get" as const },
    "sendEmail": { path: "/3/invoices/{DocumentNumber}/email" as const, method: "get" as const },
    "sendEprint": { path: "/3/invoices/{DocumentNumber}/eprint" as const, method: "get" as const },
    "markAsSent": { path: "/3/invoices/{DocumentNumber}/externalprint" as const, method: "put" as const },
    "getPreview": { path: "/3/invoices/{DocumentNumber}/preview" as const, method: "get" as const },
    "print": { path: "/3/invoices/{DocumentNumber}/print" as const, method: "get" as const },
    "printReminder": { path: "/3/invoices/{DocumentNumber}/printreminder" as const, method: "get" as const },
    "setWarehouseReady": { path: "/3/invoices/{DocumentNumber}/warehouseready" as const, method: "put" as const },
  },
  "labels": {
    "getList": { path: "/3/labels" as const, method: "get" as const },
    "create": { path: "/3/labels" as const, method: "post" as const },
    "update": { path: "/3/labels/{Id}" as const, method: "put" as const },
    "delete": { path: "/3/labels/{Id}" as const, method: "delete" as const },
  },
  "me": {
    "get": { path: "/3/me" as const, method: "get" as const },
  },
  "modesofpayments": {
    "getList": { path: "/3/modesofpayments" as const, method: "get" as const },
    "create": { path: "/3/modesofpayments" as const, method: "post" as const },
    "get": { path: "/3/modesofpayments/{Code}" as const, method: "get" as const },
    "update": { path: "/3/modesofpayments/{Code}" as const, method: "put" as const },
    "delete": { path: "/3/modesofpayments/{Code}" as const, method: "delete" as const },
  },
  "noxfinansinvoices": {
    "send": { path: "/3/noxfinansinvoices" as const, method: "post" as const },
    "get": { path: "/3/noxfinansinvoices/{InvoiceNumber}" as const, method: "get" as const },
    "pause": { path: "/3/noxfinansinvoices/{InvoiceNumber}/pause" as const, method: "put" as const },
    "reportPayment": { path: "/3/noxfinansinvoices/{InvoiceNumber}/report-payment" as const, method: "put" as const },
    "stop": { path: "/3/noxfinansinvoices/{InvoiceNumber}/stop" as const, method: "put" as const },
    "takeFees": { path: "/3/noxfinansinvoices/{InvoiceNumber}/take-fees" as const, method: "put" as const },
    "unpause": { path: "/3/noxfinansinvoices/{InvoiceNumber}/unpause" as const, method: "put" as const },
  },
  "offers": {
    "getList": { path: "/3/offers" as const, method: "get" as const },
    "create": { path: "/3/offers" as const, method: "post" as const },
    "get": { path: "/3/offers/{DocumentNumber}" as const, method: "get" as const },
    "update": { path: "/3/offers/{DocumentNumber}" as const, method: "put" as const },
    "cancel": { path: "/3/offers/{DocumentNumber}/cancel" as const, method: "put" as const },
    "createInvoice": { path: "/3/offers/{DocumentNumber}/createinvoice" as const, method: "put" as const },
    "createOrder": { path: "/3/offers/{DocumentNumber}/createorder" as const, method: "put" as const },
    "sendEmail": { path: "/3/offers/{DocumentNumber}/email" as const, method: "get" as const },
    "markAsSent": { path: "/3/offers/{DocumentNumber}/externalprint" as const, method: "put" as const },
    "getPreview": { path: "/3/offers/{DocumentNumber}/preview" as const, method: "get" as const },
    "print": { path: "/3/offers/{DocumentNumber}/print" as const, method: "get" as const },
  },
  "orders": {
    "getList": { path: "/3/orders" as const, method: "get" as const },
    "create": { path: "/3/orders" as const, method: "post" as const },
    "get": { path: "/3/orders/{DocumentNumber}" as const, method: "get" as const },
    "update": { path: "/3/orders/{DocumentNumber}" as const, method: "put" as const },
    "cancel": { path: "/3/orders/{DocumentNumber}/cancel" as const, method: "put" as const },
    "createInvoice": { path: "/3/orders/{DocumentNumber}/createinvoice" as const, method: "put" as const },
    "sendEmail": { path: "/3/orders/{DocumentNumber}/email" as const, method: "get" as const },
    "markAsSent": { path: "/3/orders/{DocumentNumber}/externalprint" as const, method: "put" as const },
    "getPreview": { path: "/3/orders/{DocumentNumber}/preview" as const, method: "get" as const },
    "print": { path: "/3/orders/{DocumentNumber}/print" as const, method: "get" as const },
  },
  "predefinedaccounts": {
    "getList": { path: "/3/predefinedaccounts" as const, method: "get" as const },
    "get": { path: "/3/predefinedaccounts/{name}" as const, method: "get" as const },
    "update": { path: "/3/predefinedaccounts/{name}" as const, method: "put" as const },
  },
  "predefinedvoucherseries": {
    "getList": { path: "/3/predefinedvoucherseries" as const, method: "get" as const },
    "get": { path: "/3/predefinedvoucherseries/{Name}" as const, method: "get" as const },
    "update": { path: "/3/predefinedvoucherseries/{Name}" as const, method: "put" as const },
  },
  "pricelists": {
    "getList": { path: "/3/pricelists" as const, method: "get" as const },
    "create": { path: "/3/pricelists" as const, method: "post" as const },
    "get": { path: "/3/pricelists/{Code}" as const, method: "get" as const },
    "update": { path: "/3/pricelists/{Code}" as const, method: "put" as const },
  },
  "prices": {
    "getList": { path: "/3/prices" as const, method: "get" as const },
    "create": { path: "/3/prices" as const, method: "post" as const },
    "getSubList": { path: "/3/prices/sublist/{PriceList}/{ArticleNumber}" as const, method: "get" as const },
    "get": { path: "/3/prices/{PriceList}/{ArticleNumber}" as const, method: "get" as const },
    "update": { path: "/3/prices/{PriceList}/{ArticleNumber}" as const, method: "put" as const },
    "getByFromQuantity": { path: "/3/prices/{PriceList}/{ArticleNumber}/{FromQuantity}" as const, method: "get" as const },
    "updateByFromQuantity": { path: "/3/prices/{PriceList}/{ArticleNumber}/{FromQuantity}" as const, method: "put" as const },
    "deleteByFromQuantity": { path: "/3/prices/{PriceList}/{ArticleNumber}/{FromQuantity}" as const, method: "delete" as const },
  },
  "printtemplates": {
    "getList": { path: "/3/printtemplates" as const, method: "get" as const },
  },
  "projects": {
    "getList": { path: "/3/projects" as const, method: "get" as const },
    "create": { path: "/3/projects" as const, method: "post" as const },
    "get": { path: "/3/projects/{ProjectNumber}" as const, method: "get" as const },
    "update": { path: "/3/projects/{ProjectNumber}" as const, method: "put" as const },
    "delete": { path: "/3/projects/{ProjectNumber}" as const, method: "delete" as const },
  },
  "salarytransactions": {
    "getList": { path: "/3/salarytransactions" as const, method: "get" as const },
    "create": { path: "/3/salarytransactions" as const, method: "post" as const },
    "get": { path: "/3/salarytransactions/{SalaryRow}" as const, method: "get" as const },
    "update": { path: "/3/salarytransactions/{SalaryRow}" as const, method: "put" as const },
    "delete": { path: "/3/salarytransactions/{SalaryRow}" as const, method: "delete" as const },
  },
  "scheduletimes": {
    "get": { path: "/3/scheduletimes/{EmployeeId}/{Date}" as const, method: "get" as const },
    "update": { path: "/3/scheduletimes/{EmployeeId}/{Date}" as const, method: "put" as const },
    "resetDay": { path: "/3/scheduletimes/{EmployeeId}/{Date}/resetday" as const, method: "put" as const },
  },
  "settings": {
    "getCompanySettings": { path: "/3/settings/company" as const, method: "get" as const },
    "getLockedPeriod": { path: "/3/settings/lockedperiod" as const, method: "get" as const },
  },
  "sie": {
    "get": { path: "/3/sie/{Type}" as const, method: "get" as const },
  },
  "supplierinvoiceaccruals": {
    "getList": { path: "/3/supplierinvoiceaccruals" as const, method: "get" as const },
    "create": { path: "/3/supplierinvoiceaccruals" as const, method: "post" as const },
    "get": { path: "/3/supplierinvoiceaccruals/{SupplierInvoiceNumber}" as const, method: "get" as const },
    "update": { path: "/3/supplierinvoiceaccruals/{SupplierInvoiceNumber}" as const, method: "put" as const },
    "delete": { path: "/3/supplierinvoiceaccruals/{SupplierInvoiceNumber}" as const, method: "delete" as const },
  },
  "supplierinvoiceexternalurlconnections": {
    "create": { path: "/3/supplierinvoiceexternalurlconnections" as const, method: "post" as const },
    "get": { path: "/3/supplierinvoiceexternalurlconnections/{Id}" as const, method: "get" as const },
    "update": { path: "/3/supplierinvoiceexternalurlconnections/{Id}" as const, method: "put" as const },
    "delete": { path: "/3/supplierinvoiceexternalurlconnections/{Id}" as const, method: "delete" as const },
  },
  "supplierinvoicefileconnections": {
    "getList": { path: "/3/supplierinvoicefileconnections" as const, method: "get" as const },
    "create": { path: "/3/supplierinvoicefileconnections" as const, method: "post" as const },
    "get": { path: "/3/supplierinvoicefileconnections/{FileId}" as const, method: "get" as const },
    "delete": { path: "/3/supplierinvoicefileconnections/{FileId}" as const, method: "delete" as const },
  },
  "supplierinvoicepayments": {
    "getList": { path: "/3/supplierinvoicepayments" as const, method: "get" as const },
    "create": { path: "/3/supplierinvoicepayments" as const, method: "post" as const },
    "get": { path: "/3/supplierinvoicepayments/{Number}" as const, method: "get" as const },
    "update": { path: "/3/supplierinvoicepayments/{Number}" as const, method: "put" as const },
    "delete": { path: "/3/supplierinvoicepayments/{Number}" as const, method: "delete" as const },
    "bookkeep": { path: "/3/supplierinvoicepayments/{Number}/bookkeep" as const, method: "put" as const },
  },
  "supplierinvoices": {
    "getList": { path: "/3/supplierinvoices" as const, method: "get" as const },
    "create": { path: "/3/supplierinvoices" as const, method: "post" as const },
    "get": { path: "/3/supplierinvoices/{GivenNumber}" as const, method: "get" as const },
    "update": { path: "/3/supplierinvoices/{GivenNumber}" as const, method: "put" as const },
    "approvalBookkeep": { path: "/3/supplierinvoices/{GivenNumber}/approvalbookkeep" as const, method: "put" as const },
    "approvalPayment": { path: "/3/supplierinvoices/{GivenNumber}/approvalpayment" as const, method: "put" as const },
    "bookkeep": { path: "/3/supplierinvoices/{GivenNumber}/bookkeep" as const, method: "put" as const },
    "cancel": { path: "/3/supplierinvoices/{GivenNumber}/cancel" as const, method: "put" as const },
    "credit": { path: "/3/supplierinvoices/{GivenNumber}/credit" as const, method: "put" as const },
  },
  "suppliers": {
    "getList": { path: "/3/suppliers" as const, method: "get" as const },
    "create": { path: "/3/suppliers" as const, method: "post" as const },
    "get": { path: "/3/suppliers/{SupplierNumber}" as const, method: "get" as const },
    "update": { path: "/3/suppliers/{SupplierNumber}" as const, method: "put" as const },
  },
  "taxreductions": {
    "getList": { path: "/3/taxreductions" as const, method: "get" as const },
    "create": { path: "/3/taxreductions" as const, method: "post" as const },
    "get": { path: "/3/taxreductions/{Id}" as const, method: "get" as const },
    "update": { path: "/3/taxreductions/{Id}" as const, method: "put" as const },
    "delete": { path: "/3/taxreductions/{Id}" as const, method: "delete" as const },
  },
  "termsofdeliveries": {
    "getList": { path: "/3/termsofdeliveries" as const, method: "get" as const },
    "create": { path: "/3/termsofdeliveries" as const, method: "post" as const },
    "get": { path: "/3/termsofdeliveries/{Code}" as const, method: "get" as const },
    "update": { path: "/3/termsofdeliveries/{Code}" as const, method: "put" as const },
  },
  "termsofpayments": {
    "getList": { path: "/3/termsofpayments" as const, method: "get" as const },
    "create": { path: "/3/termsofpayments" as const, method: "post" as const },
    "get": { path: "/3/termsofpayments/{Code}" as const, method: "get" as const },
    "update": { path: "/3/termsofpayments/{Code}" as const, method: "put" as const },
    "delete": { path: "/3/termsofpayments/{Code}" as const, method: "delete" as const },
  },
  "time": {
    "listArticles": { path: "/api/time/articles-v1" as const, method: "get" as const },
    "listRegistrations": { path: "/api/time/registrations-v2" as const, method: "get" as const },
  },
  "units": {
    "getList": { path: "/3/units" as const, method: "get" as const },
    "create": { path: "/3/units" as const, method: "post" as const },
    "get": { path: "/3/units/{Code}" as const, method: "get" as const },
    "update": { path: "/3/units/{Code}" as const, method: "put" as const },
    "delete": { path: "/3/units/{Code}" as const, method: "delete" as const },
  },
  "vacationdebtbasis": {
    "get": { path: "/3/vacationdebtbasis/{Year}/{Month}" as const, method: "get" as const },
  },
  "voucherfileconnections": {
    "getList": { path: "/3/voucherfileconnections" as const, method: "get" as const },
    "create": { path: "/3/voucherfileconnections" as const, method: "post" as const },
    "get": { path: "/3/voucherfileconnections/{FileId}" as const, method: "get" as const },
    "delete": { path: "/3/voucherfileconnections/{FileId}" as const, method: "delete" as const },
  },
  "vouchers": {
    "getList": { path: "/3/vouchers" as const, method: "get" as const },
    "create": { path: "/3/vouchers" as const, method: "post" as const },
    "getSubList": { path: "/3/vouchers/sublist" as const, method: "get" as const },
    "getSubListBySeries": { path: "/3/vouchers/sublist/{VoucherSeries}" as const, method: "get" as const },
    "get": { path: "/3/vouchers/{VoucherSeries}/{VoucherNumber}" as const, method: "get" as const },
  },
  "voucherseries": {
    "getList": { path: "/3/voucherseries" as const, method: "get" as const },
    "create": { path: "/3/voucherseries" as const, method: "post" as const },
    "get": { path: "/3/voucherseries/{Code}" as const, method: "get" as const },
    "update": { path: "/3/voucherseries/{Code}" as const, method: "put" as const },
  },
  "warehouse": {
    "listDeliveries": { path: "/api/warehouse/deliveries-v1" as const, method: "get" as const },
    "createInbound": { path: "/api/warehouse/deliveries-v1/inbounddeliveries" as const, method: "post" as const },
    "getInbound": { path: "/api/warehouse/deliveries-v1/inbounddeliveries/{id}" as const, method: "get" as const },
    "updateInbound": { path: "/api/warehouse/deliveries-v1/inbounddeliveries/{id}" as const, method: "put" as const },
    "updateInboundNote": { path: "/api/warehouse/deliveries-v1/inbounddeliveries/{id}" as const, method: "patch" as const },
    "releaseInbound": { path: "/api/warehouse/deliveries-v1/inbounddeliveries/{id}/release" as const, method: "put" as const },
    "voidInbound": { path: "/api/warehouse/deliveries-v1/inbounddeliveries/{id}/void" as const, method: "put" as const },
    "createOutbound": { path: "/api/warehouse/deliveries-v1/outbounddeliveries" as const, method: "post" as const },
    "getOutbound": { path: "/api/warehouse/deliveries-v1/outbounddeliveries/{id}" as const, method: "get" as const },
    "updateOutbound": { path: "/api/warehouse/deliveries-v1/outbounddeliveries/{id}" as const, method: "put" as const },
    "updateOutboundNote": { path: "/api/warehouse/deliveries-v1/outbounddeliveries/{id}" as const, method: "patch" as const },
    "releaseOutbound": { path: "/api/warehouse/deliveries-v1/outbounddeliveries/{id}/release" as const, method: "put" as const },
    "voidOutbound": { path: "/api/warehouse/deliveries-v1/outbounddeliveries/{id}/void" as const, method: "put" as const },
    "listDocumentTypes": { path: "/api/warehouse/documentdeliveries/custom/documenttypes-v1" as const, method: "get" as const },
    "createDocumentType": { path: "/api/warehouse/documentdeliveries/custom/documenttypes-v1" as const, method: "post" as const },
    "getDocumentType": { path: "/api/warehouse/documentdeliveries/custom/documenttypes-v1/{type}" as const, method: "get" as const },
    "getCustomInbound": { path: "/api/warehouse/documentdeliveries/custom/inbound-v1/{type}/{id}" as const, method: "get" as const },
    "saveCustomInbound": { path: "/api/warehouse/documentdeliveries/custom/inbound-v1/{type}/{id}" as const, method: "put" as const },
    "releaseCustomInbound": { path: "/api/warehouse/documentdeliveries/custom/inbound-v1/{type}/{id}/release" as const, method: "put" as const },
    "voidCustomInbound": { path: "/api/warehouse/documentdeliveries/custom/inbound-v1/{type}/{id}/void" as const, method: "put" as const },
    "getCustomOutbound": { path: "/api/warehouse/documentdeliveries/custom/outbound-v1/{type}/{id}" as const, method: "get" as const },
    "saveCustomOutbound": { path: "/api/warehouse/documentdeliveries/custom/outbound-v1/{type}/{id}" as const, method: "put" as const },
    "releaseCustomOutbound": { path: "/api/warehouse/documentdeliveries/custom/outbound-v1/{type}/{id}/release" as const, method: "put" as const },
    "voidCustomOutbound": { path: "/api/warehouse/documentdeliveries/custom/outbound-v1/{type}/{id}/void" as const, method: "put" as const },
    "listIncomingGoods": { path: "/api/warehouse/incominggoods-v1" as const, method: "get" as const },
    "createIncomingGoods": { path: "/api/warehouse/incominggoods-v1" as const, method: "post" as const },
    "getIncomingGoods": { path: "/api/warehouse/incominggoods-v1/{id}" as const, method: "get" as const },
    "saveIncomingGoods": { path: "/api/warehouse/incominggoods-v1/{id}" as const, method: "put" as const },
    "updateIncomingGoodsNote": { path: "/api/warehouse/incominggoods-v1/{id}" as const, method: "patch" as const },
    "setIncomingGoodsCompleted": { path: "/api/warehouse/incominggoods-v1/{id}/completed" as const, method: "put" as const },
    "releaseIncomingGoods": { path: "/api/warehouse/incominggoods-v1/{id}/release" as const, method: "put" as const },
    "voidIncomingGoods": { path: "/api/warehouse/incominggoods-v1/{id}/void" as const, method: "put" as const },
    "listProductionOrders": { path: "/api/warehouse/productionorders-v1" as const, method: "get" as const },
    "createProductionOrder": { path: "/api/warehouse/productionorders-v1" as const, method: "post" as const },
    "getBillOfMaterials": { path: "/api/warehouse/productionorders-v1/billofmaterials/{itemId}" as const, method: "get" as const },
    "releaseProductionOrder": { path: "/api/warehouse/productionorders-v1/release/{id}" as const, method: "put" as const },
    "voidProductionOrder": { path: "/api/warehouse/productionorders-v1/void/{id}" as const, method: "put" as const },
    "getProductionOrder": { path: "/api/warehouse/productionorders-v1/{id}" as const, method: "get" as const },
    "updateProductionOrder": { path: "/api/warehouse/productionorders-v1/{id}" as const, method: "put" as const },
    "updateProductionOrderNote": { path: "/api/warehouse/productionorders-v1/{id}" as const, method: "patch" as const },
    "listPurchaseOrders": { path: "/api/warehouse/purchaseorders-v1" as const, method: "get" as const },
    "createPurchaseOrder": { path: "/api/warehouse/purchaseorders-v1" as const, method: "post" as const },
    "getCsvReport": { path: "/api/warehouse/purchaseorders-v1/csv" as const, method: "get" as const },
    "batchUpdateResponseState": { path: "/api/warehouse/purchaseorders-v1/response" as const, method: "put" as const },
    "sendMany": { path: "/api/warehouse/purchaseorders-v1/sendpurchaseorders" as const, method: "post" as const },
    "getPurchaseOrder": { path: "/api/warehouse/purchaseorders-v1/{id}" as const, method: "get" as const },
    "updatePurchaseOrder": { path: "/api/warehouse/purchaseorders-v1/{id}" as const, method: "put" as const },
    "setManuallyCompleted": { path: "/api/warehouse/purchaseorders-v1/{id}/complete" as const, method: "put" as const },
    "setDropshipCompleted": { path: "/api/warehouse/purchaseorders-v1/{id}/dropshipcomplete" as const, method: "put" as const },
    "getMatchedDocuments": { path: "/api/warehouse/purchaseorders-v1/{id}/matches" as const, method: "get" as const },
    "getNotes": { path: "/api/warehouse/purchaseorders-v1/{id}/notes" as const, method: "get" as const },
    "updatePartial": { path: "/api/warehouse/purchaseorders-v1/{id}/partial" as const, method: "patch" as const },
    "updateResponseState": { path: "/api/warehouse/purchaseorders-v1/{id}/response" as const, method: "put" as const },
    "send": { path: "/api/warehouse/purchaseorders-v1/{id}/send" as const, method: "post" as const },
    "voidPurchaseOrder": { path: "/api/warehouse/purchaseorders-v1/{id}/void" as const, method: "put" as const },
    "getStockBalance": { path: "/api/warehouse/status-v1/stockbalance" as const, method: "get" as const },
    "listStockPoints": { path: "/api/warehouse/stockpoints-v1" as const, method: "get" as const },
    "createStockPoint": { path: "/api/warehouse/stockpoints-v1" as const, method: "post" as const },
    "getManyStockPoints": { path: "/api/warehouse/stockpoints-v1/multi" as const, method: "get" as const },
    "getStockPoint": { path: "/api/warehouse/stockpoints-v1/{id}" as const, method: "get" as const },
    "appendStockLocations": { path: "/api/warehouse/stockpoints-v1/{id}" as const, method: "post" as const },
    "updateStockPoint": { path: "/api/warehouse/stockpoints-v1/{id}" as const, method: "put" as const },
    "deleteStockPoint": { path: "/api/warehouse/stockpoints-v1/{id}" as const, method: "delete" as const },
    "listStockLocations": { path: "/api/warehouse/stockpoints-v1/{id}/stocklocations" as const, method: "get" as const },
    "listStockTakings": { path: "/api/warehouse/stocktaking-v1" as const, method: "get" as const },
    "createStockTaking": { path: "/api/warehouse/stocktaking-v1" as const, method: "post" as const },
    "getStockTaking": { path: "/api/warehouse/stocktaking-v1/{id}" as const, method: "get" as const },
    "updateStockTaking": { path: "/api/warehouse/stocktaking-v1/{id}" as const, method: "put" as const },
    "deleteStockTaking": { path: "/api/warehouse/stocktaking-v1/{id}" as const, method: "delete" as const },
    "addRowsByFilter": { path: "/api/warehouse/stocktaking-v1/{id}/addrows" as const, method: "post" as const },
    "getCandidateRows": { path: "/api/warehouse/stocktaking-v1/{id}/candidates" as const, method: "get" as const },
    "releaseStockTaking": { path: "/api/warehouse/stocktaking-v1/{id}/release" as const, method: "put" as const },
    "listRows": { path: "/api/warehouse/stocktaking-v1/{id}/rows" as const, method: "get" as const },
    "addRows": { path: "/api/warehouse/stocktaking-v1/{id}/rows" as const, method: "post" as const },
    "deleteRowsByFilter": { path: "/api/warehouse/stocktaking-v1/{id}/rows" as const, method: "delete" as const },
    "deleteRow": { path: "/api/warehouse/stocktaking-v1/{id}/rows/{rowId}" as const, method: "delete" as const },
    "voidStockTaking": { path: "/api/warehouse/stocktaking-v1/{id}/void" as const, method: "put" as const },
    "createStockTransfer": { path: "/api/warehouse/stocktransfer-v1" as const, method: "post" as const },
    "getStockTransfer": { path: "/api/warehouse/stocktransfer-v1/{id}" as const, method: "get" as const },
    "updateStockTransfer": { path: "/api/warehouse/stocktransfer-v1/{id}" as const, method: "put" as const },
    "releaseStockTransfer": { path: "/api/warehouse/stocktransfer-v1/{id}/release" as const, method: "put" as const },
    "voidStockTransfer": { path: "/api/warehouse/stocktransfer-v1/{id}/void" as const, method: "put" as const },
    "getActivationStatus": { path: "/api/warehouse/tenants-v4" as const, method: "get" as const },
  },
  "wayofdeliveries": {
    "getList": { path: "/3/wayofdeliveries" as const, method: "get" as const },
    "create": { path: "/3/wayofdeliveries" as const, method: "post" as const },
    "get": { path: "/3/wayofdeliveries/{Code}" as const, method: "get" as const },
    "update": { path: "/3/wayofdeliveries/{Code}" as const, method: "put" as const },
    "delete": { path: "/3/wayofdeliveries/{Code}" as const, method: "delete" as const },
  },
} as const;

export type ResourceOperations = typeof RESOURCE_OPERATIONS;
